set(_CATKIN_CURRENT_PACKAGE "xycar_slam")
set(xycar_slam_VERSION "0.0.0")
set(xycar_slam_MAINTAINER "srko <srko@todo.todo>")
set(xycar_slam_PACKAGE_FORMAT "2")
set(xycar_slam_BUILD_DEPENDS )
set(xycar_slam_BUILD_EXPORT_DEPENDS )
set(xycar_slam_BUILDTOOL_DEPENDS "catkin")
set(xycar_slam_BUILDTOOL_EXPORT_DEPENDS )
set(xycar_slam_EXEC_DEPENDS )
set(xycar_slam_RUN_DEPENDS )
set(xycar_slam_TEST_DEPENDS )
set(xycar_slam_DOC_DEPENDS )
set(xycar_slam_URL_WEBSITE "")
set(xycar_slam_URL_BUGTRACKER "")
set(xycar_slam_URL_REPOSITORY "")
set(xycar_slam_DEPRECATED "")